package io.hsar.mathhammer.cli.input

enum class Ability {
    FLAMER,
    ON_6_TO_WOUND_MORTAL_WOUND,
    BLAST,
    EXTRA_ATTACK_ON_CHARGE,
    EXTRA_ATTACK,
    DOUBLE_ATTACKS,
    ON_1_TO_HIT_REROLL,
    ON_6_TO_HIT_TWO_EXTRA_HITS,
    HEAVY_WEAPON_EXTRA_AP,
    ASSAULT_AND_RAPID_FIRE_EXTRA_AP,
    MELEE_EXTRA_AP
}