package io.hsar.mathhammer.cli.input

enum class WeaponAbility {
    BLAST,
    ASSAULT,
    RAPID_FIRE,
    HEAVY,
    PISTOL,
    AUTO_HIT,

    //    EXTRA_ATTACK_ON_CHARGE,
    CRITS_ON,
    EXTRA_ATTACKS,
    ON_1_TO_HIT_REROLL,
    ON_1_TO_WOUND_REROLL,
    ON_ALL_TO_HIT_REROLL,
    ON_ALL_TO_WOUND_REROLL,
    ON_CRIT_TO_HIT_EXTRA_HITS,
    ON_CRIT_TO_HIT_AUTO_WOUND,
    ON_CRIT_TO_WOUND_MORTAL_WOUNDS,
    ANTI,
//    HEAVY_WEAPON_EXTRA_AP,
//    ASSAULT_AND_RAPID_FIRE_EXTRA_AP,
//    MELEE_EXTRA_AP,
}